server:
  port: 7001

logging:
  level:
    root: INFO

mybatis-plus:
  global-config:
    banner: false

knife4j:
  enable: false
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: false
    enable-home-custom: true
    enable-swagger-models: false
    home-custom-path: classpath:README.md

sa-token:
  token-name: satoken
  timeout: 2592000
  is-log: true
  is-print: false

config:
  uid-cookie-name: 'deviceUid'    # 匿名用户 cookie 名称
  uid-cookie-path: "/"            # 匿名用户 cookie 路径
  uid-cookie-max-age: 315360000   # 10 年（秒）

spring:
  servlet:
    multipart:
      max-file-size: 10MB       # 单个文件最大10MB
      max-request-size: 50MB    # 单次请求总大小50MB
      file-size-threshold: 2MB  # 可选：内存缓存阈值
      enabled: true             # 可选：开启上传支持